### ISSUE TITLE
Implement additional validator monitoring for consensus debugging

### ISSUE THREAD

**Issue by deedlau** [FreeTON-Network/FreeTON-Node#2]
Sometimes consensus in TON network may hang due to various reasons. In most cases 2/3 of validators can't agree on some stage. So it is important to have clear understanding which stage hangs now and how the issue may be resolved without network restart. To achieve this monitoring tools should be connected based on a simple idea:
- all validators implements extra logging with to a separate file with timestamps and some case specific fields;
- all files are gathered together in Log Stash for further analysing.

There are a few places in C++ implementation which may be logged, see attached PDF: [Validator_Monitoring.pdf](https://github.com/FreeTON-Network/FreeTON-Node/files/5033708/Validator_Monitoring.pdf)

Thanks to Mitja for this.

**Comment by 01399** [comment]
There is numbers. Sync lost in q13
