### ISSUE TITLE
"run-clang-format.sh" script is broken

### ISSUE THREAD

**Issue by zxcat** [FreeTON-Network/FreeTON-Node#3]
It tries to call `src.sh` which is not in the repo: https://github.com/FreeTON-Network/FreeTON-Node/blob/2a4ed655722ef2dd8d055e34d8c0ea36cea66c2b/run-clang-format.sh#L1-L2

**Comment by deedlau** [comment]
One of the missing pieces from the original TON team, unfortunately.

**Comment by ilyar** [comment]
файл `./src.sh` просто выводит список файлов для форматирования и для того чтобы его восстановить надо просто прийти к договоренности что форматировать через clang-format.

есть конфиг форматирования `.clang-format` уже это можно использовать следующим образом: https://github.com/FreeTON-Network/FreeTON-Node/pull/4
